#!/bin/bash
# dash-queue.sh — Manage the Action Queue on Adam's dash
# Owner: Brain
#
# Usage:
#   dash-queue.sh add "title" [type] [priority] [source]
#   dash-queue.sh done <id>
#   dash-queue.sh remove <id>
#   dash-queue.sh list
#   dash-queue.sh rebuild   # regenerates the HTML action-queue section
#
# Types: task, email, invoice, draft, reminder, setup, approval
# Priority: high (red), medium (amber), low (blue)
# Source: brain, nbhw, cairr, bts, v3dn, property, gridpilot
set -uo pipefail

QUEUE_JSON="/Users/cairr/.openclaw/agents/command-centre/workspace/dev/dashboard/action-queue.json"
DASH_HTML="/Users/cairr/.openclaw/agents/command-centre/workspace/dev/dashboard/dashboard.html"

ACTION="${1:-list}"
shift || true

case "$ACTION" in
  add)
    TITLE="${1:?Usage: dash-queue.sh add \"title\" [type] [priority] [source]}"
    TYPE="${2:-task}"
    PRIORITY="${3:-medium}"
    SOURCE="${4:-brain}"
    ID="aq-$(date +%s)"
    CREATED="$(date '+%Y-%m-%dT%H:%M%z')"
    
    # Add to JSON using python (jq not guaranteed on macOS)
    python3 -c "
import json, sys
with open('$QUEUE_JSON', 'r') as f:
    q = json.load(f)
q.append({'id':'$ID','type':'$TYPE','priority':'$PRIORITY','source':'$SOURCE','title':sys.argv[1],'created':'$CREATED','status':'pending'})
with open('$QUEUE_JSON', 'w') as f:
    json.dump(q, f, indent=2)
print(f'✅ Added $ID: {sys.argv[1]}')
" "$TITLE"
    ;;
    
  done|remove)
    TARGET_ID="${1:?Usage: dash-queue.sh done/remove <id>}"
    python3 -c "
import json
with open('$QUEUE_JSON', 'r') as f:
    q = json.load(f)
q = [i for i in q if i['id'] != '$TARGET_ID']
with open('$QUEUE_JSON', 'w') as f:
    json.dump(q, f, indent=2)
print(f'✅ Removed $TARGET_ID')
"
    ;;
    
  list)
    python3 -c "
import json
with open('$QUEUE_JSON', 'r') as f:
    q = json.load(f)
if not q:
    print('📭 Queue empty')
else:
    for i in q:
        icon = {'high':'🔴','medium':'🟡','low':'🔵'}.get(i['priority'],'⚪')
        typ = {'email':'📧','invoice':'💰','draft':'✏️','reminder':'⏰','setup':'🔧','approval':'✅','task':'📋'}.get(i['type'],'📋')
        print(f\"{icon} {typ} [{i['id']}] [{i['source']}] {i['title']}\")
"
    ;;
    
  rebuild)
    # Generate HTML snippet and inject into dashboard
    python3 << 'PYEOF'
import json, re

QUEUE_JSON = "/Users/cairr/.openclaw/agents/command-centre/workspace/dev/dashboard/action-queue.json"
DASH_HTML = "/Users/cairr/.openclaw/agents/command-centre/workspace/dev/dashboard/dashboard.html"

with open(QUEUE_JSON, 'r') as f:
    q = json.load(f)

# Sort: high first, then medium, then low
order = {'high': 0, 'medium': 1, 'low': 2}
q.sort(key=lambda x: order.get(x.get('priority', 'medium'), 1))

# Build HTML
lines = []
lines.append('  <!-- ACTION QUEUE - auto-generated by dash-queue.sh rebuild -->')
lines.append('  <div class="action-queue" style="grid-column: 1 / -1; background: #111; border: 2px solid #f59e0b; border-radius: 10px; padding: 12px 14px; margin-bottom: 4px;">')
lines.append('    <div style="font-size:11px; color:#f59e0b; font-weight:700; margin-bottom:8px;">⚡ ACTION QUEUE — Needs Your Input</div>')

if not q:
    lines.append('    <div style="font-size:10px; color:#555;">📭 Nothing pending — all clear!</div>')
else:
    for item in q:
        dot_class = {'high': 're', 'medium': 'y', 'low': 'b'}.get(item.get('priority', 'medium'), 'y')
        type_icon = {'email': '📧', 'invoice': '💰', 'draft': '✏️', 'reminder': '⏰', 'setup': '🔧', 'approval': '✅', 'task': '📋'}.get(item.get('type', 'task'), '📋')
        source = item.get('source', '').upper()
        title = item.get('title', '')
        lines.append(f'    <div class="r"><span class="d {dot_class}"></span>{type_icon} <span style="color:#555;font-size:8px;">[{source}]</span> {title}</div>')

lines.append('  </div>')
lines.append('  <!-- END ACTION QUEUE -->')

html_block = '\n'.join(lines)

# Read dashboard
with open(DASH_HTML, 'r') as f:
    html = f.read()

# Remove old action queue if exists
html = re.sub(r'  <!-- ACTION QUEUE.*?<!-- END ACTION QUEUE -->\n?', '', html, flags=re.DOTALL)

# Insert after the dates-card closing div (before the first project card)
# Find the closing </div> of dates-card, then the next blank line or card
insert_marker = '<!-- NBHW -->'
if insert_marker in html:
    html = html.replace(insert_marker, html_block + '\n\n  ' + insert_marker)
else:
    # Fallback: insert before first .card div
    html = html.replace('  <div class="card">', html_block + '\n\n  <div class="card">', 1)

with open(DASH_HTML, 'w') as f:
    f.write(html)

print(f"✅ Rebuilt action queue in dashboard ({len(q)} items)")
PYEOF
    ;;
    
  *)
    echo "Usage: dash-queue.sh [add|done|remove|list|rebuild]"
    exit 1
    ;;
esac
